### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by ThomasArdal** [elmah/Bootstrapper#1]
This is so awesome! Would be great with an example application showing how to configure a logger using this code (like the SQL Server logger).

**Comment by atifaziz** [comment]
You think the instructions in the [README](https://github.com/elmah/Bootstrapper/blob/master/README.md) are not simple enough?

**Comment by ThomasArdal** [comment]
You're propably right about the fact that the readme is fine for the SQL based error loggers. I was thinking about how to extend it for something like [Elmah.Elasticsearch](https://github.com/elmahio/Elmah.Io.ElasticSearch).

**Comment by atifaziz** [comment]
Bootstrapper does cheat and has the unfair advantage that it knows all the `ErrorLog` implementations that have shipped as part of ELMAH so it has [them all hard-wired](https://github.com/elmah/Bootstrapper/blob/v1.0.0-beta-2/Bootstrapper.cs#L233-242). An alternative approach would be to use [MEF](https://msdn.microsoft.com/en-us/library/dd460648%28v=vs.110%29.aspx) for discovery but then you still need some way to select the desired `ErrorLog` based on some convention.

Yet another approach would be for you to create a bootstrapper that's specific to Elmah.Elasticsearch and that uses this project as a dependency. All your bootstrapper would then need to do is [install an `IServiceProvider` implementation](https://github.com/elmah/Bootstrapper/blob/v1.0.0-beta-2/Bootstrapper.cs#L151) to supply your `ElasticSearchErrorLog` if the application follows some convention you define (like `<appSettings>` section contains at least one key prefixed `elmah:elasticsearch:`).

**Comment by ThomasArdal** [comment]
cc: @jayhilden

**Comment by ThomasArdal** [comment]
Would be awesome with some sort of configuration API, making all this possible from C# code as well. Could be something like this:

```
new ElmahConfiguration()
    .SQLiteErrorLog("Data Source=c:\mydb.db;Version=3;")
    .Create();
```

This would make it possible to create extension methods in the different NuGet package containing thirdparty loggers like this:

```
new ElmahConfiguration()
    .ElasticSearchErrorLog("http://localhost:9200") <-- This would come from Elmah.Elasticsearch
    .Create();
```

**Comment by atifaziz** [comment]
@ThomasArdal I was hoping to avoid introducing a new API with this as it might defeat the purpose of having a bootstrapping helper in the first place. Also, would you want to re-compile and re-deploy your project if the URL into `ElasticSearchErrorLog` needs changing?  Wouldn't you end up picking up that URL from configuration settings?

**Comment by ThomasArdal** [comment]
@atifaziz Agree. A bootstrapper like this should work out of the box. A configuration API could be another package (on that I've talked about in the past).

Anyway I think this discussion branched from the original issue description :) The improved wiki definitely made it more clear how to use this.

**Comment by atifaziz** [comment]
Oops. Bad x-ref to this issue when f8cca5e8ddb64b4a66fb5481ff324cb4814d7fca addresses #5.
