### ISSUE TITLE
How does the Bootstrapper package compare to Elmah.MVC

### ISSUE THREAD

**Issue by RudeySH** [elmah/Bootstrapper#11]
The third party [Elmah.MVC](https://github.com/alexbeletsky/elmah-mvc) has always been my go-to package when adding Elmah to an MVC application. However, in doing so, I am not using the bootstrapper. 

Both packages provide similar features; no further configuration required after installig, the URL becomes `/elmah` instead of `/elmah.axd`, various configurable app settings are introduced, authorization, etc.

When should I use this package instead of Elmah.MVC? Or should both be used at the same time?

**Comment by atifaziz** [comment]
ELMAH Bootstrapper is for ASP.NET applications in general whereas Elmah.MVC provides specific integration for applications using the ASP.NET MVC framework. They both use the same technique to bootstrap ELMAH into the application.

> Or should both be used at the same time?

Certainly not.

> When should I use this package instead of Elmah.MVC?

If you're not using ASP.NET MVC.

**Comment by RudeySH** [comment]
Thanks, that clears things up.
