### ISSUE TITLE
In-Memory Error Log Does Not Display Application Name

### ISSUE THREAD

**Issue by MarcChasse** [elmah/Bootstrapper#9]
When you don't specify a storage mechanism no name is displayed on the error log page:
![image](https://user-images.githubusercontent.com/6767724/33153786-2e106124-cfa1-11e7-90b4-e6233a38707b.png)
I've got the app name in my web.config:
``` xml
<appSettings>
  <add key="elmah:applicationName" value="My App Name Here" />
</appSettings>
```
but it looks like line 283 doesn't pass any configuration into MemoryErrorLog Class:
```c#
     : new Func<ErrorLog>(() => new MemoryErrorLog()));
```

Unless I missed something I think this could be fixed by passing config to `MemoryErrorLog`.

Thanks!

**Comment by atifaziz** [comment]
@MarcChasse Thanks for reporting this and you are spot on with the bug!

**Comment by atifaziz** [comment]
[Version 1.0.1 has been published](https://www.nuget.org/packages/elmah.bootstrapper/1.0.1), which contains this bug fix.
